<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>example</groupId>
  <artifactId>classpath-requires-0.1.13</artifactId>
  <version>1.0-SNAPSHOT</version>

  <build>
    <plugins>
      <plugin>
        <groupId>@project.groupId@</groupId>
        <artifactId>@project.artifactId@</artifactId>
        <version>@project.version@</version>
        <dependencies>
          <dependency>
            <groupId>org.choral-lang</groupId>
            <artifactId>choral</artifactId>
            <version>0.1.12</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <goals>
              <goal>epp</goal>
            </goals>
            <configuration>
              <symbol>HelloRoles</symbol>
              <classpathEntries>
                <classpathEntry>${project.basedir}</classpathEntry>
              </classpathEntries>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
